### ISSUE TITLE
How do I run this script in order to batch save images?

### ISSUE THREAD

**Issue by JB2448** [kavin-90/Scrappers#1]
I am attempting to save volumes of Pocket Monsters Special while they are on Sunday Web Every for a limited time (https://www.sunday-webry.com/events/pokemon_sp_rubysapphire/), and your php script would help a great deal in expediting the process. I have no experience with running php scripts. Is there an easy way that I can use the one you've made to save these pages?

**Comment by kavin-90** [comment]
To use it you need PHP first download it from http://windows.php.net/ download it then extract in your desire location now type command `php -S sunday_web_every.php`

for more info on PHP WebServer http://php.net/manual/en/features.commandline.webserver.php

or Download Repo then Extract **php.zip** and open **WelPressed.exe** give path of where Nginx and PHP is done. Now Move php file into html folder and browse `localhost/sunday_web_every.php`

in `sunday_web_every.php` in last line change url of series you want to download and done.

Series Folder and Chapter Folder automatically will be created and image will be saved in chapter folder.

**Comment by kavin-90** [comment]
Thanks for Notify me . I've update Sunday Web Every Scrapper.

Fixed. If 1060 image size does not exists fallback to 713 file Image sizes.

Now it support Events Series Also :smile: 

@JB2448 works?
